Repository OasisLMF/ODS_Tools, pull requests merged in 2023-06, with the labels that each got.

#27 fix read_csv only read needed line when reading header
  ods_tools/oed/source.py
  tests/test_ods_package.py
Labels: bug

#36 Fix Settings compatibility for older workers
  ods_tools/main.py
  ods_tools/oed/setting_schema.py
Labels: bug, Backport fix

#41 fix check category
  ods_tools/oed/source.py
Labels: bug

#46 add option to manage unknown column when saving files
  ods_tools/oed/__init__.py
  ods_tools/oed/common.py
  ods_tools/oed/exposure.py
  ods_tools/oed/source.py
  tests/test_ods_package.py
Labels: feature
