Repository OasisLMF/ODS_Tools, pull requests merged in 2024-05, with the labels that each got.

#109 Update OED spec to 3.2.0
  setup.py
Labels: LTS - 2.3

#115 fix issue when categorical column have a default value
  ods_tools/oed/source.py
  tests/test_ods_package.py
Labels: bug, Backport fix

#111 Removed 'ord_output' from valid_metrics in model-settings
  ods_tools/data/model_settings_schema.json
  tests/test_ods_package.py
Labels: bug, LTS - 2.3

#113 Remove summary groups max value
  ods_tools/data/analysis_settings_schema.json
Labels: LTS - 2.3

#117 Fix/fill empty
  ods_tools/oed/__init__.py
  ods_tools/oed/common.py
  ods_tools/oed/exposure.py
  ods_tools/oed/oed_schema.py
  ods_tools/oed/source.py
  ods_tools/oed/validator.py
  tests/test_ods_package.py
Labels: LTS - 2.3
