Repository OasisLMF/ODS_Tools, pull requests merged in 2025-01, with the labels that each got.

#170 Update OED schema to release v4
  setup.py
Labels: feature, LTS - 2.4

#169 Fix default for do_disaggregation to true
  ods_tools/data/analysis_settings_schema.json
  ods_tools/data/model_settings_schema.json
Labels: LTS - 2.3, LTS - 2.4

#172 CI Fix - branches renamed in OED repo
  .github/workflows/build.yml
Labels: bug, LTS - 2.3, LTS - 2.4

#146 OED Settings merger
  ods_tools/data/analysis_settings_schema.json
  ods_tools/data/model_settings_schema.json
  ods_tools/oed/__init__.py
  ods_tools/oed/setting_schema.py
  ods_tools/oed/settings.py
  tests/data/analysis_settings.json
  tests/data/computation_settings_schema.json
  tests/data/config_compatibility_profile.json
  tests/data/model_compatibility_profile.json
  tests/data/model_settings.json
  tests/test_ods_package.py
  tests/test_settings.py
Labels: feature, LTS - 2.4
